### ISSUE TITLE
Planning ahead for submissions

### ISSUE THREAD

**Issue by rapvil** [EpicSevenDB/gamedatabase#18]
A quick question...

So, what would be the best way to divide and conquer the items/skills/units/artifacts we PR? 
The idea is that we don't want people to work on things others are already working on... 
We can kind of only 'claim' we're working on things once the PR goes up... but what if it's too late by then... 

3 options I feel:

1. Make small and fast complete PRs. Ideally 1 artifact/item/hero per, potentially a nightmare to maintain PRs.
2. 'Claim' a group of units in an empty PR and slowly add to it, have it open for like a week max or something and tag head boss when PR is done and ready.
3. Maintain a wiki or something to say "Here's a list of units pending, here are the users who have claimed them"

**Comment by kmalone86** [comment]
I am not sure which is best, but this is a good idea. It takes a good amount of time to write up a hero. I imagine RaphaelDDL has his hands full with the constant stream of PRs to review. I am not sure flooding the PR list will make that any easier.  We could just open an issue with a list of everything needed and people can just comment on what they are working on and edit their comment when needed.  A wiki page would probably be cleaner if we have one setup.

**Comment by kevin-quach** [comment]
I think for one of the issues you mentioned, github has a Kanban board we can utilize for anyone looking to seriously contribute to help keep things organized on who is working on what. At lease for this early in development a smaller dedicated team might be better. 

As for heroes, I'm currently making a simple tool that takes form inputs and turns it into the json object he needs since the hero object is pretty large.

**Comment by RaphaelDDL** [comment]
> Make small and fast complete PRs. Ideally 1 artifact/item/hero per, potentially a nightmare to maintain PRs.

I actually think small PRs are better than one with tons. Both because it's more meaningful commit message but as well I can review and merge faster when I get time. When it's a big one (like #7), I had to take a while to read. Not much difference, but it'll take a while longer to review since I'll be reading each file when I'm not doing any client work.

On the other hand, for the contributors, it'll be a lot of branching hell. I'm used to, some might not.


> Maintain a wiki or something to say "Here's a list of units pending, here are the users who have claimed them"

I created a simple Wiki page and added @rapvil @kmalone86 @Triharder-E7 @kevin-quach as team Collaborators, so you'll be able to edit the wiki too. You'll also have option to review and merge PRs , as 
well as (probably) merge directly to master (please do not do that lol).


Github has project boards too, I'll try read and understand how it work, I've seen it being used on vue-cli (https://github.com/vuejs/vue-cli/projects). Maybe we could do the same. For the project, you can add a PR or an issue as part of the list, so maybe suggestion number 2 `'Claim' a group of units in an empty PR and slowly add to it, have it open for like a week max or something and tag head boss when PR is done and ready.` is the best to go with Projects.

What you think?

**Comment by kmalone86** [comment]
I updated the wiki to have a list of all the heroes alphabetized, so we can track what still needs to be done.

Projects do sounds interesting.

**Comment by infininight** [comment]
Checklists are supported if one of you wants to update the list to:

https://gist.github.com/infininight/d9a8080172b2165ef217c8da33fafa3e

**Comment by Triharder-E7** [comment]
I may be dumb, as I've no real experience with github, but I can't seem to edit the wiki page. I intend to slowly make my way through the 3 star heroes, as others seem to be doing the occasional 4 and 5 star ones. 

The next 5 I intend to work through are, in no particular order:
Butcher Corps Inquisitor
Taranor Royal Guard
Pyllis
Bask
Judith

I've no idea how to do separate pull requests for each hero commit when I have multiples at once, so I think after my Aither request gets merged I will just open a pull request once I've finished one of the 5 above and add heroes to it as I complete them. You can just approve that whenever you manage to catch up, and I'll start a new pull request and continue the trend. If I hit 5 heroes on one pull request, I will stop until you've had time to check them all, so it's not too large. Let me know if that works for you @RaphaelDDL or if I need to do something else! 👍

**Comment by Triharder-E7** [comment]
Google has shown me the error of my ways. I didn't realize I had an email asking me to be a collaborator that required my accepting. I'm all set now, thanks! 😄

**Comment by infininight** [comment]
@kmalone86 A pull request points to a branch, so it will always reflect the current state of that branch. To create a second pull request you just need to create a second branch, etc.

**Comment by RaphaelDDL** [comment]
@kmalone86 Yup, I'm totally fine 👍 
And good point, rule of thumb, never merge your own.

I'll be fair and stop being dumb by merging my changes directly to master and also make PRs so you guys can be in sync, like I just did in https://github.com/EpicSevenDB/gamedatabase/compare/c72e4a7ff2ba60c9b03517771ad26567e19912f0..a9c387f9a4678408feb420e5de4d961f012453ef (added prettier and git hooks to format file when making a commit. npm install again in case there's any error to get the dependencies)

**Comment by rapvil** [comment]
I'm not seeing the edit 😢 

![image](https://user-images.githubusercontent.com/23729253/49320790-ca4ffe00-f557-11e8-9fe2-d0fb9b10c5fc.png)

Was reserving Achates, Wanda and Guider Aither after my current PR... will most likely do those separately

**Comment by Triharder-E7** [comment]
@rapvil Check your email linked to your github account for a collaboration request for this repository. Once you accept that, you should be able to edit it. I'll go ahead and update the wiki with the heroes you mentioned though 😄

**Comment by kmalone86** [comment]
I just added wiki pages on skill enhancement. When filling out a hero, you can just copy and paste the generic skill enhance items from the hero's respected base star level. After just replace the rare-catalyst and epic-catalyst based on Zodiac symbol in base Enhancement Resource page.

**Comment by kmalone86** [comment]
@RaphaelDDL 
It looks like next week will be a bit of a shack up in heroes. Sounds like all the skill enhancements items for 4\*/5\* will be completely changed. Is there a way we could have a centralized skill enhancement .json rather than having to copy it to every hero?  This update by itself will cause a lot of data to be wrong and will be hard to go back to every hero to fix.

Maybe another variable.  Just some ideas below, but don't know how the main database will handle this.
enhance-leo-maxlevel6-level1
enh-items-leo-6-1

"enhancement": [{
                "description": "+15% damage dealt", "resources": ["enh_items_leo_6_1"]
            }, {

**Comment by RaphaelDDL** [comment]
@kmalone86 I actually didn't notice the materials were equal based on the zodiac sign #noobhere

Yes, if after patch we notice same approach (I'm assuming they'll be different based on rarity now, if I understood dev notes right), we can do this. And actually resources can just be a string, since it'll be a key to a list of items.

**Comment by kmalone86** [comment]
Oops, I forgot base star lvl. Currently every hero with the same zodiac and base star lvl will have to same enhance items.  The amount of items does vary based on how many levels of upgrades the skill has.
So something like this when adding in base rarity, "enh_items_leo_base5_6_1".

We will have to update all the base/max stats as well, but I have not seen a pattern there, so each hero will have to be updated manually for that sadly.

We will probably need an example of the string method, as I know I am not super familiar with it

**Comment by RaphaelDDL** [comment]
I mean, you suggested:

     "description": "+15% damage dealt", "resources": ["enh_items_leo_6_1"]

Could just be 

     "description": "+15% damage dealt", "resources": "enh_items_leo_6_1"

> We will have to update all the base/max stats as well, but I have not seen a pattern there, so each hero will have to be updated manually for that sadly.

Yeah, "roughly 6% for base 5 stars, 3% for 4 stars".. ugh ..

**Comment by kmalone86** [comment]
Right, but would we need enh_items_leo_base5_6_1.json files like all the buff_debuffs?

**Comment by kmalone86** [comment]
Right.
{sign}_{hero_rarity}_{skill type/max rank}_{skill rank/upgrade}

Just saying _6_1 for type and rank may be too confusing at first glace. Not sure what would be the least confusing words to use.
{sign}_rarity{1-5}_max{2-7}_rank{1-7}
{sign}_base{1-5}_type{2-7}_lvl{1-7}

**Comment by kmalone86** [comment]
@RaphaelDDL 

I have updated the wiki for skill enhancement after patch (except 5\* max4 as I don't have one) and everything still looks to follow the same updated values as expected.  I am not sure what format the JSON needs to be in order to work well with the database, otherwise I would start creating them.

leo_rarity5_max7_rank7.json
``
{
``
``
    "title": "Enhancement Cost: Leo, Rarity 5, Max rank 7, Rank 7",
``
``
    "description": "",
``
``
    "resources": [{ "item": "blazing-soul", "qty": 3 }, { "item": "molagorago", "qty": 3 }, { "item": "gold", "qty": 150000 }]
``
``
}
``

Or would it be something simple like this.

``
{ [{ "item": "blazing-soul", "qty": 3 }, { "item": "molagorago", "qty": 3 }, { "item": "gold", "qty": 150000 }] }
``

**Comment by RaphaelDDL** [comment]
I meant the info on title, `"title": "Enhancement Cost: Leo, Rarity 5, Max rank 7, Rank 7",`, It should be separated fields for rarity, etc.

But let me think this straight for a few.

**Comment by yonkishum** [comment]
Greetings I notice in the Type drop-box the Material class type doesn't appear but instead in the element drop-box appear, maybe is a visual bug?

![screenshot - 24_12_2018 09_43_47 a m](https://user-images.githubusercontent.com/6378461/50400902-19590f80-0761-11e9-938c-f0b06fc9d872.png)
![screenshot - 24_12_2018 09_43_54 a m](https://user-images.githubusercontent.com/6378461/50400903-19f1a600-0761-11e9-8408-8ad71381e2f9.png)

**Comment by kevin-quach** [comment]
Thanks for the catch! It's a mistake on my part when building the select form. I'll have that fixed.
