### ISSUE TITLE
Add hero stats for levels between 1 and 50

### ISSUE THREAD

**Issue by AlexeiA** [EpicSevenDB/gamedatabase#204]
In both API and UI the db only have heroes' stats for levels 1, 50 and 60. Whould be useful to have stats for levels 30 and 40 for 3* heroes and 40 for 4* heroes as well.

**Comment by RaphaelDDL** [comment]
From what I was seeing, status are more like a good to see that answer the following two questions:
- "should I make unit 6 star or keep as 5?"
- "should I fully awaken or not? Does it matter on the stats that much?".
 
Which is why we have 50 with and without awakening, as well as 60 with and without awakening.

Can you give me a better idea on the reasons you thought for having 30 and 40? I mean, why someone would not want to either 5 or 6 star an unit they are going to use?

**Comment by AlexeiA** [comment]
Well, the same questions can arise about promoting 3* and 4* heroes too. And at least 4* to 5* promoring is not cheap. I know, only few heroes may be useful at 30 and 40, mostly in pvp, and usually their only stat that people care about is speed. But even so, it is useful to know that e.g. Judith gets her max speed at level 40 after awakening. And that Celeste needs to be 6* for that. Also if you know stats for level 40 you can rate character's tankiness or what his effectiveness value is. Of course, all that info you can find in game itself, the Journal there is very good, but the same is about other info, including lv 50 and 60 stats.
I personally just miss level 40 stats in the gear optimizer, as I use some level 40 characters and have to set their level to 50, which makes all stats values except the speed wrong.

**Comment by RaphaelDDL** [comment]
Hmm got it. So it's more to help the other tools than for the website, which makes sense.

> I am ready to add the stats myself, just need the place in JSON to add them.

Well, if you do got the data ready already, it makes a lot easier. Do you have it on a spreadsheet or something?

Do you understand JSON and how write on it? If yes, you can simply follow the standard for the others. Take J Kise as example:
https://github.com/EpicSevenDB/gamedatabase/blob/master/src/hero/judge-kise.json

Her stats start at Line37, and has a few objects inside `lv1BaseStarNoAwaken`, `lv50FiveStarNoAwaken`, `lv50FiveStarFullyAwakened`, etc..  So You would add a new object, let's say `lv40FourStarFullyAwakened` or lv40FourStarNoAwaken` and so on. 

If you don't know much of json but has a spreadsheet with it, let me know how it is arranged, I might be able to just write a converter to auto add to the jsons.

**Comment by AlexeiA** [comment]
I understand JSON, but don't have the data ready. I think I'll just type the data from the game's journal.

The only question left is should we have objects like lv40FourStarFullyAwakened for the 5* heroes (or lv30... for 4* and 5*), as IMHO this problem only arise when thinking about to promote a hero or not.

**Comment by RaphaelDDL** [comment]
Well, let's make a rule like this, we'll have lvl1 and then every MAX level per star that a unit can achieve. For example: 

## 3 star will have

- `lv1BaseStarNoAwaken` <- Existing
- `lv30tThreeStar`(`FullyAwakened` and `NoAwaken`) <- your suggestion
- `lv40FourStar`(awaken and no awaken) <- your suggestion
- `lv50FiveStarNoAwaken` <- Existing
- `lv50FiveStarFullyAwakened`  <- Existing
- `lv60SixStarNoAwaken` <- Existing
- `lv60SixStarFullyAwakened`  <- Existing


## 4 star will have

They start at lv1, their first max level being 40. So you can do:

- `lv1BaseStarNoAwaken` <- Existing
- `lv40FourStar`(awaken and no awaken) <- your suggestion
- `lv50FiveStarNoAwaken` <- Existing
- `lv50FiveStarFullyAwakened`  <- Existing
- `lv60SixStarNoAwaken` <- Existing
- `lv60SixStarFullyAwakened`  <- Existing

You see that 4 star doesn't have `lv30tThreeStar`(`FullyAwakened` and `NoAwaken`) because their first achievable MAX level is `lv40FourStar*`.

Therefore there's no changes to current nat5 heroes, as their first MAX level is already covered on the `lv50FiveStar*`.

What you think

**Comment by AlexeiA** [comment]
Yes, was thinking exactly the same!

**Comment by RaphaelDDL** [comment]
Closing this since with V2 we can calc any level with hero's bra/int/fai/des https://github.com/EpicSevenDB/api/issues/2#issuecomment-604665367

In the UI of website, there will be a slider to pick level/awakening, like artifact have now.
