### ISSUE TITLE
Please add little Queen Charlotte and Roana

### ISSUE THREAD

**Issue by Arzanp** [EpicSevenDB/gamedatabase#248]
Please add these heroes. Thanks

**Comment by Dimbreath** [comment]
They're on the API already. Raph is still porting website to v2 API. It should be done soon.

**Comment by RaphaelDDL** [comment]
And if this request was done because of the Gear Optimizer, we are tracking the Optimizer upgrade to use v2 api in here: https://github.com/Zarroc2762/E7-Gear-Optimizer/issues/43

They seem to have finished so please update to latest, and open issues on https://github.com/Zarroc2762/E7-Gear-Optimizer/issues if you see anything broke on the app.

Or if you see data wrong (game says hero A has 100 speed but it's showing a different number), then open an issue in here like you did previously.

Thank you for the report :)
